### PR TITLE
Class diagrams

### PR DESCRIPTION
**Pull request by GhostofGoes**
Need diagrams in master so I can include and test links inside SSDD

### CODE REVIEW

**Comment by ccasey645** [comment]
Hello,

Sorry about that. I meant to merge the branches sooner. I've merged all
active branches into master.

If there's something else I need to include (png of use case, or if
something else that didn't get merged) please let me know.

Casey

**Comment by GhostofGoes** [comment]
Thanks, no worries.

If you could compile the UML and have a png that'd be great.

Also, should we keep the branches? Or clean them up?

**Comment by ccasey645** [comment]
We should keep the branches with our names on them, but probably not the
"Class Diagrams" branch. We should merge master into our respective
branches to make sure we are working on the most updated code. But that
shouldn't be hard. I can do that to my branch and your branch if that is
ok. Or I can wait until tomorrow night so I don't mess up the branch you're
working on.

I pushed the pngs to the master branch. If you have problems pushing to the
master branch, make sure to pull the changes to your local machine, then
push. It should just do a fast forward merge (merge automatically). But if
you have any problems let me know.

Casey

**Comment by ccasey645** [comment]
I'll wait to delete the Class Diagrams branch until the meeting on Tuesday
so I can talk to Anton and have him make his own branch. I want to make
sure he's not working on that branch before I delete it.

Does everything look organized enough on the repo? I don't want to move
anything since it will probably affect your linking them into the SSDD.

Casey

**Comment by GhostofGoes** [comment]
Some of the misc files in doc might need to be cleaned up at some point, otherwise its easy to navigate and understand. :+1:

**Comment by ccasey645** [comment]
Cool. Yeah I'll probably tidy up the repo sometime this week.

Also, I looked over the SSDD. Looks great. Thought it would be good to do
some peer review, and it all looks good to me.

**Pull request merged**
